# Generated by Django 2.0.6 on 2018-06-24 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(default='None', max_length=255)),
                ('last', models.CharField(default='None', max_length=255)),
                ('email', models.EmailField(default='None', max_length=254)),
                ('birthday', models.DateField(default='None', null=True)),
                ('bio', models.TextField(blank=True)),
                ('pfp', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
